/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_embla-carousel@8.6.0_react@19.2.0_rolldown-vite@7.1_2a4f6ed46d9a4d20ad45abbea61b090a/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_embla-carousel@8.6.0_react@19.2.0_rolldown-vite@7.1_2a4f6ed46d9a4d20ad45abbea61b090a/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_embla-carousel@8.6.0_react@19.2.0_rolldown-vite@7.1_2a4f6ed46d9a4d20ad45abbea61b090a/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UModal: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_embla-carousel@8.6.0_react@19.2.0_rolldown-vite@7.1_2a4f6ed46d9a4d20ad45abbea61b090a/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
  }
}
