packages:
  - examples/*

catalog:
  '@bytecodealliance/jco': 1.15.1
  '@nuxt/ui': 4.1.0
  '@tailwindcss/vite': 4.1.16
  rolldown-vite: 7.1.19
  rolldown: 1.0.0-beta.44
  rollup-plugin-string-import: 1.2.6
  tailwindcss: 4.1.16
  tsdown: 0.15.9
  vite-plugin-singlefile: 2.3.0
  vue-router: 4.6.3
  vue: 3.6.0-alpha.2
